### ISSUE TITLE
TCP/IP Underlay Adapter for Skip Graph

### ISSUE THREAD

**Issue by NazirNayal8** [yhassanzadeh13/SEALA_Client#12]
* To implement a connection adapter using TCP/IP for the skip graph underlay
* This [repository](https://github.com/yhassanzadeh13/tcp-broadcast-tree) contains an functional implementation of TCP for reference
* To add unit testing.

**Comment by utkn** [comment]
Dear @NazirNayal8,

I have a few questions on the implementation before proceeding.
1. How do we handle the sessions in the TCP/IP implementations? For example, should we terminate the connection after each message is sent? Or should we keep sending "heartbeat"s to keep the connection alive? If that's the case how do we know when the connection should be terminated?
2. Am I correct to assume that the user of Underlay (i.e. overlay) will only invoke the `sendMessage` method of the overlay and `ConnectionAdapter`s are only used internally by the `Underlay` class?

**Comment by NazirNayal8** [comment]
Greetings @utkn , 

1. I assume we may terminate the connection right after the message is done, but I'm not quite sure what is best in terms of performance so I hope @yhassanzadeh13  could give us more guidance on this.

2. Yes that will be exactly the case.

**Comment by utkn** [comment]
Dear @NazirNayal8 ,

Now that I have started implementing other adapters using our design, there are several issues that I have noticed.
1. In order to decouple `ConnectionAdapter` from java RMI packages, I had to create a separate interface that extends from `Remote` since the methods need to throw a `RemoteException`. Please see my latest commit on the branch `Utkan-12-TCPAdapter`.
2. TCP does not play well with `ConnectionAdapter` design. We need to create and maintain two different adapters (host and remote). The host adapter needs to delegate the methods to the overlay, but the remote adapter needs to take the arguments and send them through a Socket. At this point, forcing a RPC-like design on TCP seems like it's going to result in unnecessarily complex code.

I propose that we simply make use of an abstract Underlay class and implement a `JavaRMIUnderlay` and `TCPUnderlay`. As you said, the only method the overlay is going to use is `sendMessage`, thus this should not be a problem. 

Of course, I can complete the implementation using our current design if you wish.

Thanks,

Utkan

**Comment by NazirNayal8** [comment]
Greetings @utkn ,

Thank you for this elaboration. So regarding TCP, the complex code you are referring to is having an extra layer to wrap the host and the remote in a direct adapter am I right ? So if I understand your suggestion correctly, having the `Underlay` to be the pluggable piece instead of the connection adapter would save us one level of additional abstraction correct ? If so I totally agree with your suggestion and I think we can proceed to implement it.
