### ISSUE TITLE
Lookup Table

### ISSUE THREAD

**Issue by NazirNayal8** [yhassanzadeh13/SEALA_Client#4]
* To Implement a Lookup Table class with the following functions:
   * `bool UpdateLeft(SkipNodeIdentity node, int level)`: updates left node in lookup table
   * `bool UpdateRight(SkipNodeIdentity node, int level)`: updates right node in lookup table
   * `SkipNodeIdentity GetRight(int level)`: returns node in given level
   * `SkipNodeIdentity GetLeft(int level)`: returns node in given level
   * `bool RemoveLeft(int level)`: removes left node in given level
   * `bool RemoveRight(int level)`: removes right node in given level.

Maybe we can also use `SkipNodeIdentity` of unique values to denote a null or empty skip node,  instead of explicitly using null.

**Comment by Shamdan17** [comment]
@NazirNayal8 How much thread safety do you want in the lookup table? This is an important issue that we should discuss asap because it could cause us issues in the future like it did earlier.

**Comment by NazirNayal8** [comment]
@Shamdan17 : That's a good point. Given that we do not have to worry about data nodes (for the moment), we only need to make access to the lookup table instance synchronized right ? What do you think ?

**Comment by Shamdan17** [comment]
I have implemented the LookupTable interface and a concurrent concrete implementation, take a look at it and tell me what you think.
As for the interface, I instead opted to use the following interface:

- SkipNodeIdentity UpdateLeft(SkipNodeIdentity node, int level): updates left node in lookup table
- SkipNodeIdentity UpdateRight(SkipNodeIdentity node, int level): updates right node in lookup table
- SkipNodeIdentity GetRight(int level): returns node in given level
- SkipNodeIdentity GetLeft(int level): returns node in given level
- SkipNodeIdentity RemoveLeft(int level): removes left node in given level
- SkipNodeIdentity RemoveRight(int level): removes right node in given level.

instead, because I feel that there might be useful information that we can get by having that in remove/update and could potentially reduce network queries (instead of get then remove, simply remove, etc). Tell me if you think otherwise

**Comment by NazirNayal8** [comment]
@Shamdan17 : Thank you for the implementation, I totally agree with your modification very nice, can you open a pull request for this ?
